######LLM GENERATED CODE BEGINS######

CC = gcc
SRC1 = ./src/main.c
SRC2 = ./src/printPrompt.c
SRC3 = ./src/parser.c

SRC = $(SRC1) $(SRC2) $(SRC3)
OUT = shell.out

all: $(OUT)

$(OUT): $(SRC)
	$(CC) $(SRC) -o $(OUT)

clean:
	rm -f $(OUT)

#####LLM GENERATED CODE ENDS######

