######LLM GENERATED CODE BEGINS######

CC = gcc
SRC1 = ./src/main.c
SRC2 = ./src/printPrompt.c
SRC3 = ./src/parser.c
SRC4 = ./src/hop.c
SRC5 = ./src/executes.c

SRC = $(SRC1) $(SRC2) $(SRC3) $(SRC4) $(SRC5)
OUT = shell.out

all: $(OUT)

$(OUT): $(SRC)
	$(CC) $(SRC) -o $(OUT)

clean:
	rm -f $(OUT)

#####LLM GENERATED CODE ENDS######

